// Data for accommodations in Ujjain
export const accommodationData = [
  {
    id: 1,
    name: "Mahakal Residency",
    type: "Hotel",
    icon: "/temple.png",
    priceCategory: "₹₹",
    distanceToGhat: "9 min walk to nearest ghat",
    shuttle: "Shuttle S-3 (3-5 min)",
    accessibility: {
      hasRamp: true,
      hasAccessibleToilet: true,
      hasLift: true,
    },
    amenities: {
      hasPowerBackup: true,
      hasWomenWing: true,
      hasFirstAid: true,
      hasWater: false,
    },
    isWheelchairFriendly: true,
    isNearShuttleHub: true,
    hasFamilyRooms: true,
  },
  {
    id: 2,
    name: "Kshipra Dharamshala",
    type: "Dharamshala",
    icon: "/temple.png",
    priceCategory: "₹₹",
    distanceToGhat: "14 min walk to nearest ghat",
    shuttle: "Shuttle S-2 (5-7 min)",
    accessibility: {
      hasRamp: true,
      hasAccessibleToilet: false,
      hasLift: false,
    },
    amenities: {
      hasPowerBackup: false,
      hasWomenWing: false,
      hasFirstAid: false,
      hasWater: true,
    },
    isWheelchairFriendly: false,
    isNearShuttleHub: true,
    hasFamilyRooms: false,
  },
  {
    id: 3,
    name: "Ujjain Tent City",
    type: "Tent Accommodation",
    icon: "/temple.png",
    priceCategory: "₹",
    distanceToGhat: "5 min walk to nearest ghat",
    shuttle: "Shuttle S-1 (2-3 min)",
    accessibility: {
      hasRamp: false,
      hasAccessibleToilet: false,
      hasLift: false,
    },
    amenities: {
      hasPowerBackup: false,
      hasWomenWing: true,
      hasFirstAid: true,
      hasWater: true,
    },
    isWheelchairFriendly: false,
    isNearShuttleHub: true,
    hasFamilyRooms: true,
  },
  {
    id: 4,
    name: "Shri Mangalnath Resort",
    type: "Resort",
    icon: "/temple.png",
    priceCategory: "₹₹₹",
    distanceToGhat: "12 min walk to nearest ghat",
    shuttle: "Shuttle S-5 (7-10 min)",
    accessibility: {
      hasRamp: true,
      hasAccessibleToilet: true,
      hasLift: true,
    },
    amenities: {
      hasPowerBackup: true,
      hasWomenWing: true,
      hasFirstAid: true,
      hasWater: true,
    },
    isWheelchairFriendly: true,
    isNearShuttleHub: false,
    hasFamilyRooms: true,
  },
];
