// Data for emergency and info services in Ujjain
export const emergencyInfoData = [
  {
    id: 1,
    name: "Police Control Room",
    icon: "/temple.png",
    category: "emergency",
    contact: "100",
    location: "Ujjain Police HQ",
    distance: "1.5 km from Ram Ghat",
    hours: "24/7",
    priority: "high",
  },
  {
    id: 2,
    name: "Ambulance Service",
    icon: "/temple.png",
    category: "emergency",
    contact: "108",
    location: "City-wide",
    distance: "Varies by location",
    hours: "24/7",
    priority: "high",
  },
  {
    id: 3,
    name: "Kumbh Mela Control Room",
    icon: "/temple.png",
    category: "emergency",
    contact: "0734-2551234",
    location: "Central Mela Office",
    distance: "0.8 km from Main Gate",
    hours: "24/7",
    priority: "high",
  },
  {
    id: 4,
    name: "Tourist Information Center",
    icon: "/temple.png",
    category: "info",
    contact: "0734-2551000",
    location: "Near Ram Ghat",
    distance: "50 m from Ram Ghat",
    hours: "6 AM - 10 PM",
    priority: "medium",
  },
  {
    id: 5,
    name: "Lost & Found Center",
    icon: "/temple.png",
    category: "info",
    contact: "0734-2551111",
    location: "Main Entrance Plaza",
    distance: "200 m from Entry Gate 1",
    hours: "6 AM - 12 AM",
    priority: "medium",
  },
  {
    id: 6,
    name: "Fire Emergency",
    icon: "/temple.png",
    category: "emergency",
    contact: "101",
    location: "City Fire Station",
    distance: "3 km from Main Area",
    hours: "24/7",
    priority: "high",
  },
  {
    id: 7,
    name: "Medical Emergency",
    icon: "/temple.png",
    category: "emergency",
    contact: "108",
    location: "All Medical Camps",
    distance: "Various Locations",
    hours: "24/7",
    priority: "high",
  },
  {
    id: 8,
    name: "Volunteer Help Desk",
    icon: "/temple.png",
    category: "info",
    contact: "0734-2552222",
    location: "All Major Entrances",
    distance: "Various Locations",
    hours: "6 AM - 10 PM",
    priority: "low",
  },
  {
    id: 9,
    name: "Event Information",
    icon: "/temple.png",
    category: "info",
    contact: "0734-2553333",
    location: "Information Kiosks",
    distance: "Various Locations",
    hours: "6 AM - 9 PM",
    priority: "low",
  }
];
