// Data for ghats in Ujjain
export const ghatsData = [
  {
    id: 1,
    name: "Ram Ghat",
    icon: "/temple.png",
    bestGate: "E-5",
    nearestTemple: "Harshiddhi Mata Temple",
    hasShade: true,
    shadeQueue: true,
    ghatLength: "100 m",
    crowdLevel: "Moderate",
    features: ["Changing Rooms", "Wash Rooms"],
    isNearFirstAid: true,
    isLowCrowd: false,
  },
  {
    id: 2,
    name: "Triveni Ghat",
    icon: "/temple.png",
    bestGate: "N-2",
    nearestTemple: "Triveni Ghat",
    isOpen: true,
    ghatLength: "120 m",
    crowdLevel: "Low",
    features: ["Changing Rooms", "Wash Rooms"],
    isNearFirstAid: false,
    isLowCrowd: true,
  },
  {
    id: 3,
    name: "Mangalnath Ghat",
    icon: "/temple.png",
    bestGate: "W-3",
    nearestTemple: "Mangalnath Temple",
    hasShade: true,
    ghatLength: "70 m",
    crowdLevel: "High",
    features: ["Changing Rooms", "Wash Rooms"],
    isNearFirstAid: true,
    isLowCrowd: false,
  },
  {
    id: 4,
    name: "Gau Ghat",
    icon: "/temple.png",
    bestGate: "S-1",
    nearestTemple: "Gau Ghat",
    hasShade: false,
    ghatLength: "80 m",
    crowdLevel: "Low",
    features: ["Morning ritual", "Shallow entry"],
    isNearFirstAid: false,
    isLowCrowd: true,
  },
  {
    id: 5,
    name: "Siddhavat Ghat",
    icon: "/temple.png",
    bestGate: "E-2",
    nearestTemple: "Siddhavat Temple",
    hasShade: true,
    ghatLength: "80 m",
    crowdLevel: "Moderate",
    features: ["Historic banyan tree", "Cool shade"],
    isNearFirstAid: false,
    isLowCrowd: false,
  },
];
