import { useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    ghats: 'Ghats',
    accommodation: 'Accommodation',
    parking: 'Parking & Shuttle',
    entryExit: 'Entry/Exit',
    temples: 'Temples',
    layers: 'Layers',
    manage: 'Manage',
    dayRoutes: 'Day & Routes',
    regularDay: 'Regular Day',
    shahiSnan: 'Shahi Snan',
    festival: 'Festival / Parva',
    dynamicRouting: 'Dynamic routing active',
    liveTraffic: 'Live traffic (5 min)',
    aiAsk: 'Ask Anubhav AI',
    send: 'Send',
    aiTitle: 'Anubhava AI',
    aiContext: 'Youre chatting about : Context',
    aiPrompt: 'Ask questions about ghats, temples or travel logistics.',
    aiPlaceholder: 'Ask about routes, amenities, timings…',
    midnightAarti: 'Midnight Aarti Theme',
    copyright: '© 2025 Ujjain Mahakumbh',
    devotionalUi: 'Indigo · Gold devotional UI',
    enHi: 'EN / HI',
    light: 'Light',
    dark: 'Dark',
  legend: 'Legend',
  menu: 'Menu',
    wards: 'Wards',
    restaurants: 'Restaurants',
    hospitals: 'Hospitals',
    hotels: 'Hotels',
    lostFound: 'Lost & Found',
    publicToilets: 'Public Toilets',
    policeStations: 'Police Stations',
    busStand: 'Bus Stand',
    atm: 'ATM',
    atms: 'ATM',
    fireStation: 'Fire Station',
    stayTents: 'Stay Tents',
    searchTemples: 'Search temples...',
    allTemples: 'All Temples',
    jyotirlinga: 'Jyotirlinga',
    shaktipeeth: 'Shaktipeeth',
    lessCrowded: 'Less crowded now',
    wheelchairFriendly: 'Wheelchair friendly',
    darshanCards: 'Darshan Cards',
    deity: 'Deity',
    darshan: 'Darshan',
    aarti: 'Aarti',
    nearestGhat: 'Nearest Ghat',
    distance: 'Distance',
    amenities: 'Amenities',
    guideMe: 'Guide me',
    save: 'Save',
    crowdLevel: 'Crowd Level',
    'Drinking Water': 'Drinking Water',
    'First Aid': 'First Aid',
    'Lockers': 'Lockers',
    'Wheelchair Access': 'Wheelchair Access',
    'Prasad Shop': 'Prasad Shop',
    'Parking': 'Parking',
    'Garden': 'Garden',
    'Seating': 'Seating',
  },
  hi: {
    home: 'होम',
    ghats: 'घाट',
    accommodation: 'आवास',
    parking: 'पार्किंग और शटल',
    entryExit: 'प्रवेश/निकास',
    temples: 'मंदिर',
    layers: 'परतें',
    manage: 'प्रबंधित करें',
    dayRoutes: 'दिन और मार्ग',
    regularDay: 'सामान्य दिन',
    shahiSnan: 'शाही स्नान',
    festival: 'त्योहार / पर्व',
    dynamicRouting: 'डायनामिक रूटिंग सक्रिय',
    liveTraffic: 'लाइव ट्रैफिक (5 मिनट)',
    aiAsk: 'अनुभव एआई से पूछें',
    send: 'भेजें',
    aiTitle: 'अनुभव एआई',
    aiContext: 'आप चैट कर रहे हैं: संदर्भ',
    aiPrompt: 'घाट, मंदिर या यात्रा के बारे में पूछें।',
    aiPlaceholder: 'मार्ग, सुविधाएं, समय पूछें…',
    midnightAarti: 'मिडनाइट आरती थीम',
    copyright: '© 2025 उज्जैन महाकुंभ',
    devotionalUi: 'इंडिगो · गोल्ड डिवोशनल यूआई',
    enHi: 'EN / HI',
    light: 'लाइट',
    dark: 'डार्क',
  legend: 'लीजेंड',
  menu: 'मेन्यू',
    // New translations
    wards: 'वार्ड्स',
    restaurants: 'रेस्टोरेंट',
    hospitals: 'अस्पताल',
    hotels: 'होटल',
    lostFound: 'खोया और पाया',
    publicToilets: 'सार्वजनिक शौचालय',
    policeStations: 'पुलिस स्टेशन',
    busStand: 'बस स्टैंड',
  atm: 'एटीएम',
  atms: 'एटीएम',
    fireStation: 'अग्निशमन केंद्र',
    stayTents: 'निवास तंबू',
    searchTemples: 'मंदिर खोजें...',
    allTemples: 'सभी मंदिर',
    jyotirlinga: 'ज्योतिर्लिंग',
    shaktipeeth: 'शक्तिपीठ',
    lessCrowded: 'अभी कम भीड़',
    wheelchairFriendly: 'व्हीलचेयर अनुकूल',
    darshanCards: 'दर्शन कार्ड',
    deity: 'देवता',
    darshan: 'दर्शन',
    aarti: 'आरती',
    nearestGhat: 'निकटतम घाट',
    distance: 'दूरी',
    amenities: 'सुविधाएं',
    guideMe: 'मुझे मार्गदर्शन करें',
    save: 'सहेजें',
    crowdLevel: 'भीड़ का स्तर',
    'Drinking Water': 'पीने का पानी',
    'First Aid': 'प्राथमिक चिकित्सा',
    'Lockers': 'लॉकर',
    'Wheelchair Access': 'व्हीलचेयर पहुंच',
    'Prasad Shop': 'प्रसाद की दुकान',
    'Parking': 'पार्किंग',
    'Garden': 'उद्यान',
    'Seating': 'बैठने की जगह',
  },
};

export function useLang() {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  return { lang, setLang, t };
}
