import { useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    ghats: 'Ghats',
    accommodation: 'Accommodation',
    parking: 'Parking & Shuttle',
    entryExit: 'Emergency/Info',
    temples: 'Temples',
    layers: 'Layers',
    manage: 'Manage',
    dayRoutes: 'Day & Routes',
    regularDay: 'Regular Day',
    shahiSnan: 'Shahi Snan',
    festival: 'Festival / Parva',
    dynamicRouting: 'Dynamic routing active',
    liveTraffic: 'Live traffic (5 min)',
    aiAsk: 'Ask Anubhav AI',
    send: 'Send',
    aiTitle: 'Anubhava AI',
    aiContext: 'Youre chatting about : Context',
    aiPrompt: 'Ask questions about ghats, temples or travel logistics.',
    aiPlaceholder: 'Ask about routes, amenities, timings…',
    midnightAarti: 'Midnight Aarti Theme',
    copyright: '© 2025 Ujjain Mahakumbh',
    devotionalUi: 'Indigo · Gold devotional UI',
    enHi: 'EN / HI',
    light: 'Light',
    dark: 'Dark',
    legend: 'Legend',
    menu: 'Menu',
    wards: 'Wards',
    restaurants: 'Restaurants',
    hospitals: 'Hospitals',
    hotels: 'Hotels',
    lostFound: 'Lost & Found',
    publicToilets: 'Public Toilets',
    policeStations: 'Police Stations',
    busStand: 'Bus Stand',
    atm: 'ATM',
    atms: 'ATM',
    fireStation: 'Fire Station',
    stayTents: 'Stay Tents',
    searchTemples: 'Search temples...',
    allTemples: 'All Temples',
    jyotirlinga: 'Jyotirlinga',
    shaktipeeth: 'Shaktipeeth',
    lessCrowded: 'Less crowded now',
    wheelchairFriendly: 'Wheelchair friendly',
    darshanCards: 'Darshan Cards',
    deity: 'Deity',
    darshan: 'Darshan',
    aarti: 'Aarti',
    nearestGhat: 'Nearest Ghat',
    distance: 'Distance',
    amenities: 'Amenities',
    guideMe: 'Guide me',
    save: 'Save',
    crowdLevel: 'Crowd Level',
    'Drinking Water': 'Drinking Water',
    'First Aid': 'First Aid',
    'Lockers': 'Lockers',
    'Wheelchair Access': 'Wheelchair Access',
    'Prasad Shop': 'Prasad Shop',
    'Parking': 'Parking',
    'Garden': 'Garden',
    'Seating': 'Seating',
    search: 'Search',
    content: 'content',
    coming: 'coming',
    soon: 'soon',
    back: 'Back',
    lowCrowd: 'Low crowd',
    barrierFree: 'Barrier-free',
    shade: 'Shade',
    nearestFirstAid: 'Nearest first-aid',
    ghatList: 'Ghat List',
    bestGate: 'Best gate',
    route: 'route',
    shadeQueue: 'Shade queue',
    water: 'Water',
    crowd: 'Crowd',
    guideSafe: 'Guide (safe)',
    alternateGhat: 'Alternate ghat',
    ghatLength: 'Length',
    nearestTemple: 'Nearest Temple',
    'Slippery steps': 'Slippery steps',
    'Keep night': 'Keep night',
    'Open sun': 'Open sun',
    'Carry water': 'Carry water',
    'Family friendly': 'Family friendly',
    'Evening aarti': 'Evening aarti',
    'Morning ritual': 'Morning ritual',
    'Shallow entry': 'Shallow entry',
    'Historic banyan tree': 'Historic banyan tree',
    'Cool shade': 'Cool shade',
    nearShuttleHub: 'Near shuttle hub',
    familyRooms: 'Family rooms',
    stayOptions: 'Stay Options',
    navigate: 'Navigate',
    call: 'Call',
    accessibility: 'Accessibility',
    ramp: 'Ramp',
    accessibleToilet: 'Accessible toilet',
    lift: 'Lift',
    powerBackup: 'Power backup',
    womenWing: 'Women wing',
    viewDetails: 'View Details',
    emergency: 'Emergency',
    info: 'Information',
    emergencyServices: 'Emergency Services',
    infoServices: 'Information Services',
    emergencyContacts: 'Emergency Contacts',
    callEmergency: 'Call Emergency',
    getDirections: 'Get Directions',
    all: 'All',
    highPriority: 'High Priority',
    mediumPriority: 'Medium Priority',
    lowPriority: 'Low Priority',
    contactInfo: 'Contact Info',
    location: 'Location',
    hours: 'Hours',
  },
  hi: {
    home: 'होम',
    ghats: 'घाट',
    accommodation: 'आवास',
    parking: 'पार्किंग और शटल',
    entryExit: 'आपातकाल/जानकारी',
    temples: 'मंदिर',
    layers: 'परतें',
    manage: 'प्रबंधित करें',
    dayRoutes: 'दिन और मार्ग',
    regularDay: 'सामान्य दिन',
    shahiSnan: 'शाही स्नान',
    festival: 'त्योहार / पर्व',
    dynamicRouting: 'डायनामिक रूटिंग सक्रिय',
    liveTraffic: 'लाइव ट्रैफिक (5 मिनट)',
    aiAsk: 'अनुभव एआई से पूछें',
    send: 'भेजें',
    aiTitle: 'अनुभव एआई',
    aiContext: 'आप चैट कर रहे हैं: संदर्भ',
    aiPrompt: 'घाट, मंदिर या यात्रा के बारे में पूछें।',
    aiPlaceholder: 'मार्ग, सुविधाएं, समय पूछें…',
    midnightAarti: 'मिडनाइट आरती थीम',
    copyright: '© 2025 उज्जैन महाकुंभ',
    devotionalUi: 'इंडिगो · गोल्ड डिवोशनल यूआई',
    enHi: 'EN / HI',
    light: 'लाइट',
    dark: 'डार्क',
    legend: 'लीजेंड',
    menu: 'मेन्यू',
    wards: 'वार्ड्स',
    restaurants: 'रेस्टोरेंट',
    hospitals: 'अस्पताल',
    hotels: 'होटल',
    lostFound: 'खोया और पाया',
    publicToilets: 'सार्वजनिक शौचालय',
    policeStations: 'पुलिस स्टेशन',
    busStand: 'बस स्टैंड',
    atm: 'एटीएम',
    atms: 'एटीएम',
    fireStation: 'अग्निशमन केंद्र',
    stayTents: 'निवास तंबू',
    searchTemples: 'मंदिर खोजें...',
    allTemples: 'सभी मंदिर',
    jyotirlinga: 'ज्योतिर्लिंग',
    shaktipeeth: 'शक्तिपीठ',
    lessCrowded: 'अभी कम भीड़',
    wheelchairFriendly: 'व्हीलचेयर अनुकूल',
    darshanCards: 'दर्शन कार्ड',
    deity: 'देवता',
    darshan: 'दर्शन',
    aarti: 'आरती',
    nearestGhat: 'निकटतम घाट',
    distance: 'दूरी',
    amenities: 'सुविधाएं',
    guideMe: 'मुझे मार्गदर्शन करें',
    save: 'सहेजें',
    crowdLevel: 'भीड़ स्तर',
    'Drinking Water': 'पीने का पानी',
    'First Aid': 'प्राथमिक चिकित्सा',
    'Lockers': 'लॉकर्स',
    'Wheelchair Access': 'व्हीलचेयर पहुंच',
    'Prasad Shop': 'प्रसाद की दुकान',
    'Parking': 'पार्किंग',
    'Garden': 'बगीचा',
    'Seating': 'बैठने की जगह',
    search: 'खोजें',
    content: 'सामग्री',
    coming: 'जल्द आ रही है',
    soon: 'जल्द ही',
    back: 'वापस',
    lowCrowd: 'कम भीड़',
    barrierFree: 'बाधा-मुक्त',
    shade: 'छाया',
    nearestFirstAid: 'नजदीकी प्राथमिक चिकित्सा',
    ghatList: 'घाट सूची',
    bestGate: 'सर्वश्रेष्ठ गेट',
    route: 'मार्ग',
    shadeQueue: 'छाया कतार',
    water: 'पानी',
    crowd: 'भीड़',
    guideSafe: 'मार्गदर्शन (सुरक्षित)',
    alternateGhat: 'वैकल्पिक घाट',
    ghatLength: 'लंबाई',
    nearestTemple: 'निकटतम मंदिर',
    'Slippery steps': 'फिसलन वाले कदम',
    'Keep night': 'रात को रखें',
    'Open sun': 'खुला सूर्य',
    'Carry water': 'पानी लेकर चलें',
    'Family friendly': 'परिवार के अनुकूल',
    'Evening aarti': 'शाम की आरती',
    'Morning ritual': 'सुबह का अनुष्ठान',
    'Shallow entry': 'उथला प्रवेश',
    'Historic banyan tree': 'ऐतिहासिक बरगद का पेड़',
    'Cool shade': 'ठंडी छाया',
    nearShuttleHub: 'शटल हब के पास',
    familyRooms: 'परिवार के कमरे',
    stayOptions: 'ठहरने के विकल्प',
    navigate: 'नेविगेट करें',
    call: 'कॉल',
    accessibility: 'पहुंच',
    ramp: 'रैंप',
    accessibleToilet: 'सुलभ शौचालय',
    lift: 'लिफ्ट',
    powerBackup: 'पावर बैकअप',
    womenWing: 'महिला विंग',
    viewDetails: 'विवरण देखें',
    emergency: 'आपातकाल',
    info: 'जानकारी',
    emergencyServices: 'आपातकालीन सेवाएं',
    infoServices: 'सूचना सेवाएं',
    emergencyContacts: 'आपातकालीन संपर्क',
    callEmergency: 'आपातकाल पर कॉल करें',
    getDirections: 'दिशा-निर्देश प्राप्त करें',
    all: 'सभी',
    highPriority: 'उच्च प्राथमिकता',
    mediumPriority: 'मध्यम प्राथमिकता',
    lowPriority: 'कम प्राथमिकता',
    contactInfo: 'संपर्क जानकारी',
    location: 'स्थान',
    hours: 'कार्य घंटे',
    crowdLevel: 'भीड़ का स्तर',
    'Drinking Water': 'पीने का पानी',
    'First Aid': 'प्राथमिक चिकित्सा',
    'Lockers': 'लॉकर',
    'Wheelchair Access': 'व्हीलचेयर पहुंच',
    'Prasad Shop': 'प्रसाद की दुकान',
    'Parking': 'पार्किंग',
    'Garden': 'उद्यान',
    'Seating': 'बैठने की जगह',
  },
};

export function useLang() {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  return { lang, setLang, t };
}
